Fixed parameter substitution
Summary:
Use parameter substitution to do dirname not basename.

Reproducing:
Run valine while the /var/lib/valine directory does not exist.

Expected:
mkdir: cannot create directory ‘/var/lib/valine’: Permission denied
Error: Missing [and unable to create] needed directory '/var/lib/valine'
As root, execute:
  mkdir -m 2775 /var/lib/valine; chgrp libvirt /var/lib/valine

Actual:
/home/mc/bin/valine: line 332: /var/lib/valine/mydomain: No such file or directory
/home/mc/bin/valine: line 352: /var/lib/valine/mydomain: No such file or directory
Warning: mydomain config file has improper CfgVersion ('0Sifr' expected)
Storage displayed for this domain might not be accurate
If this causes problems, delete /var/lib/valine/mydomain